### ISSUE TITLE
QM config name

### ISSUE THREAD

**Issue by alecandido** [qiboteam/qibolab#1015]
https://github.com/qiboteam/qibolab/blob/888753403e496f843d67dd398b3f8ec424ee3749/src/qibolab/instruments/qm/config/config.py#L22-L23

https://github.com/qiboteam/qibolab/blob/888753403e496f843d67dd398b3f8ec424ee3749/src/qibolab/instruments/qm/components/configs.py#L44

And they are two very different things (the one documented is private, the other public :P).

We could rename:
- **`QmConfig`**: to `Configurations` (as `program()` is not `qm_program()`), and
- **`QmConfigs`**: to `QmSettings`, or `QmParameters`

or anything like that. One of the two could stay as it is, or we can change both.

Since the second will be part of the interface, better deciding before 0.2.

**Comment by stavros11** [comment]
I agree with renaming `QmConfig` to `Configurations` since it is private and already under the QM driver, so it is clear what it is refering to.

However, I would probably keep `QmConfigs` (the public one) as it is, as it is pretty descriptive of what the object is for: some additional QM specific configs (which are even the `Config` type).
