### ISSUE TITLE
Modify Qblox drivers to support final frequencies instead of intermediate and local oscillator frequencies 

### ISSUE THREAD

**Issue by aorgazf** [qiboteam/qibolab#191]
With this issue I would like to log @maxhant request for modifying qblox drivers so that they can process pulses with final frequencies instead of intermediate and local oscillator frequencies.
The implementation of this feature will require a function in the driver to best select the lo and ifs required to implement all pulses in a sequence and minimise noise (or maximise fidelity)

**Comment by andrea-pasquale** [comment]
As part of the first round of refactoring (PR #262 which is now merged to main) I've introduced a few changes to the `MultiQubitPlatform` in order to process pulses with final frequencies. 
See for example here:
https://github.com/qiboteam/qibolab/blob/687fd8820b039c5db241136122b5d3dbab41e312/src/qibolab/platforms/multiqubit.py#L115-L131
This is similar to the approach that @aorgazf proposed when we merged qiboteam/qibocal#155.
I've not tested this code with a multiqubit chip controlled by qblox (because it is not currently available) but I know that this is not the ideal solution. 

I've just realized that the status of this issue is `Done`. Should we do something else about this issue @aorgazf ?
