### ISSUE TITLE
Deployment workflow

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibolab#277]
Add github workflows for deployment, following the approach implemented in qibo.

**Comment by AleCandido** [comment]
@scarrazza this should have been solved by #278, modulo the same patch of
https://github.com/qiboteam/qibo/commit/0d715694bb48e4a0f6108c79bacbba672f9294de
still to be applied.

Since wheels are being built, should we consider this issue completed, or do you believe is still missing something? (of course I don't know if there is yet a secret for PyPI, but this is really a detail...)
