### ISSUE TITLE
Single `InstrumentDesign` object

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibolab#307]
@aorgazf suggested to have a single `InstrumentDesign` that supports different kinds of instruments (like the current `MultiqubitPlatform`), instead of the current approach where we have the basic design and the one with mixers and local oscillators. One motivation for this is that there may be instruments, such as the SPI, which do not fall to either of the above categories and maybe it would also better accommodate the qblox cluster and Zurich Instruments which have LOs but they are embedded in the controllers, unlike QM.

I am planning to open a PR and give this a try, so that we can compare with the current approach. I open this issue as reminder until I do so.

**Comment by scarrazza** [comment]
I see the motivation but are planning to create 2 `BasicInstrumentDesing` inheritances ( `SingleInstrumentDesign` and `MixerInstrumentDesign`)? Or something else? In fact, the current code has some extra complexities, almost due to the multiqubit platform, e.g.:
- `BasicInstrumentDesign` could be converted to an `AbstractInstrumentDesign` class
- `DesignPlatform` could be merged in the `AbstractPlatform`
