### ISSUE TITLE
Consolidate sweeper delay & start

### ISSUE THREAD

**Issue by aorgazf** [qiboteam/qibolab#475]
Currently we have two different ways of sweeping the time at which a pulse is played.
delay
pulse start

Ideally we would like to converge to only one method.

**Comment by Jacfomg** [comment]
This is my propose for the T2 experiment from in qibocal '#333' 

``` python
# RX90 - t - RX90 - MZ
ro_pulses = {}
RX90_pulses1 = {}
RX90_pulses2 = {}
sequence = PulseSequence()
for qubit in qubits:
    RX90_pulses1[qubit] = platform.create_RX90_pulse(qubit, start=0)
    RX90_pulses2[qubit] = platform.create_RX90_pulse(
        qubit,
        start=RX90_pulses1[qubit].finish,
    )
    ro_pulses[qubit] = platform.create_qubit_readout_pulse(
        qubit, start=RX90_pulses2[qubit].finish
    )
    sequence.add(RX90_pulses1[qubit])
    sequence.add(RX90_pulses2[qubit])
    sequence.add(ro_pulses[qubit]

sweeper = Sweeper(
    Parameter.delay,
    waits,
    [RX90_pulses1[qubit] for qubit in qubits],
)
```

For me I just understand each pulse as two things.

1. Play the wave.
2. Delay for the next.

So the delay in this case should be part of the 1st pulse. That way when I get a sweeper I get both elements instead of having to check the last element of the sequence for the sweeper.values to apply the delay and the next to know the pulse on my loop. Maybe It's just the way I coded the driver but it seemed more straigtforward.

**Comment by stavros11** [comment]
Personally, I agree with @rodolfocarobene comment here https://github.com/qiboteam/qibocal/pull/333#discussion_r1211562306 that we should only have a sweeper for `start`, not `delay`, because then it is clearer what it means. Also, in all other cases (amplitude, frequency) the sweeper `Parameter` name is one-to-one with the `Pulse` parameter.

The QM driver currently follows this convention, treating the `delay` as the `start`. That also means that qiboteam/qibocal#333 requires some changes to work for me. I am fine with changing the driver to follow @Jacfomg convention if most people prefer it. We just need to be consistent in all drivers. What is the convention used by qblox and rfsoc?

**Comment by rodolfocarobene** [comment]
For the RFSoC there aren't yet time sweepers in main (now in development, #474) but I followed the same convention of QM considering delay as equivalent to start.

From a discussion with @aorgazf, I think also Qblox follows the same convention.
