### ISSUE TITLE
Pulse simplification

### ISSUE THREAD

**Issue by alecandido** [qiboteam/qibolab#683]
The class `Pulse` is rather consistent, but in principle achieving a simple task: collecting the attributes describing a pulse.

I believe it outgrew, and it is not being touched since long, so we could take the chance of #682 to simplify it a bit.

<details><summary>Completed</summary>

- [x] the way the `__init__` is written already resembles a `dataclass`, but without many advantages of it
    https://github.com/qiboteam/qibolab/blob/2cdd14f7551a5373078f93db40db938efc069326/src/qibolab/pulses.py#L673-L701
- [x] there is some apparent duplication
    https://github.com/qiboteam/qibolab/blob/2cdd14f7551a5373078f93db40db938efc069326/src/qibolab/pulses.py#L689
    https://github.com/qiboteam/qibolab/blob/2cdd14f7551a5373078f93db40db938efc069326/src/qibolab/pulses.py#L704
    but it is there to support the symbolic expressions
    https://github.com/qiboteam/qibolab/blob/2cdd14f7551a5373078f93db40db938efc069326/src/qibolab/pulses.py#L765-L808
    that could have been useful in the past, but they are not currently used to implement sweepers, and they are potentially fully superseded by the unrolling #618.
    So we could avoid supporting the doubling in `__init__` (usage of setters).
- [x] because of the former point, most of the properties are actually not needed 
    - we can keep things like `.finish`
    - `.finish` in particular requires `.start`, and it would be delegated to `PulseSequence` following #682, same for `.global_phase`, since all *global*-related (i.e. sequence) properties should be obtained from the *global* container, `PulseSequence`, and keep the individual `Pulse` local (also for better modularity and decoupling)
- [x] `.serial` is making use of Python syntax to stringify the content, and it would require a string evaluation to load
    https://github.com/qiboteam/qibolab/blob/2cdd14f7551a5373078f93db40db938efc069326/src/qibolab/pulses.py#L1025-L1029
    this is the kind of thing we will get for "free" from dataclasses (serialization and deserialization)
- [x] often `.serial` is (ab)used to identify the pulse, but an actual `.id` attribute exists
    https://github.com/qiboteam/qibolab/blob/2cdd14f7551a5373078f93db40db938efc069326/src/qibolab/pulses.py#L1031-L1033
    it makes use of the built-in `id()` mechanism, implementation-specific (though the uniqueness within a process is guaranteed), and in CPython is obtained from the memory allocation; using [`uuid`](https://docs.python.org/3/library/uuid.html) (stdlib) should be a better replacement for this use case (better than current `.id`, but much better than `.serial`) - it could be added as a normal attribute, and set by default through a `default_factory`
- [x] these dunders we're getting from the dataclass (possibly frozen) for free
    https://github.com/qiboteam/qibolab/blob/2cdd14f7551a5373078f93db40db938efc069326/src/qibolab/pulses.py#L1071-L1080
- [x] while these others are better suited for the `PulseSequence` itself (no need to implement a feature many times)
    https://github.com/qiboteam/qibolab/blob/2cdd14f7551a5373078f93db40db938efc069326/src/qibolab/pulses.py#L1082-L1097
- [x] the copy mechanics is made much more difficult by the usage of specific subclasses of `Pulse`, that are redundant with `.type`
    https://github.com/qiboteam/qibolab/blob/2cdd14f7551a5373078f93db40db938efc069326/src/qibolab/pulses.py#L1099-L1159
    I would suggest relying on standard copy mechanism (like stdlib `copy` library) and avoid the subclasses altogether
- [x]  a `plot` is nice to have, and I would keep, but separated from the `Pulse` class itself (just taking a `Pulse` as parameter) and possibly even in a separate module
    https://github.com/qiboteam/qibolab/blob/2cdd14f7551a5373078f93db40db938efc069326/src/qibolab/pulses.py#L1174-L1259

Regarding the `Pulse` subclasses:
- [x] the only special item of `ReadoutPulse` is
    https://github.com/qiboteam/qibolab/blob/2cdd14f7551a5373078f93db40db938efc069326/src/qibolab/pulses.py#L1297-L1301
    it could be implemented (at `PulseSequence`-level) with a branching (`if` on type)
- [x] `DrivePulse` is adding nothing particular to `Pulse`
- [x] the `FluxPulse` is redirecting all the waveforms to `envelope_waveform_i`
    https://github.com/qiboteam/qibolab/blob/2cdd14f7551a5373078f93db40db938efc069326/src/qibolab/pulses.py#L1378-L1400
    I don't know the rationale, so it might be worth keeping, but I find it confusing in general: it's more transparent if the downstream writes directly `modulated_waveform_q`, rather than `envelope_waveform_i` that gets silently redirected to the former.
    However, it might be useful to apply uniform operations to all pulse types. But if this is not strictly needed, I would avoid reimplementing the property (in case, better to return a `None`, or raise an error)

Then there are *additional* pulse subclasses, that are not directly related to `.type`:
- [x] `CouplerFluxPulse` is subclassing `FluxPulse`, adding its own specific mechanism of `.PULSE_TYPE`
    https://github.com/qiboteam/qibolab/blob/2cdd14f7551a5373078f93db40db938efc069326/src/qibolab/pulses.py#L1407-L1412
    not used by any other type.
    It is a recent addition, and all the current mechanisms are not taken into account (e.g. `.copy` would lose its type, turning it in a generic `Pulse`).
    I would drop it completely, since a `CouplerFluxPulse` should be just a regular `FluxPulse` played on a `Coupler` qubit, and recognizable from the `.qubit` attribute
- [x] I have to investigate more the `SplitPulse` and where its used

Moreover:
- [x] `PulseConstructor` is definitely duplicating `PulseType` (a consequence of the subclasses duplication of the `.type` attribute)
    https://github.com/qiboteam/qibolab/blob/2cdd14f7551a5373078f93db40db938efc069326/src/qibolab/pulses.py#L1605-L1610
    https://github.com/qiboteam/qibolab/blob/2cdd14f7551a5373078f93db40db938efc069326/src/qibolab/pulses.py#L14-L25

- [x] `Waveform` should be an alias for `Callable[[int], float]` (or the vectorized version as well)
    https://github.com/qiboteam/qibolab/blob/c6f41c2a115929dd5ccc9f2471870fbf25536665/src/qibolab/pulses.py#L28-L94
    no need for plotting (it's just going to be an array, it could be plotted in the pulse) and no need for equality comparison

Btw, `PulseSequence` is reimplementing most of the API of `list`
https://github.com/qiboteam/qibolab/blob/2cdd14f7551a5373078f93db40db938efc069326/src/qibolab/pulses.py#L1733-L1752
https://github.com/qiboteam/qibolab/blob/2cdd14f7551a5373078f93db40db938efc069326/src/qibolab/pulses.py#L1627-L1643
- [x] we could consider subclassing `list` directly.

</details> 

- [ ] the start-independent comparison is caused by having a start in the first place
    https://github.com/qiboteam/qibolab/blob/2cdd14f7551a5373078f93db40db938efc069326/src/qibolab/pulses.py#L1161-L1172
    it will become the standard equality (provided by dataclasses) once the object will be local again

- [ ] I would also rename `.type` to `.channel_type`; or even better, infer the channel type from the `.channel` attribute (since `.type` is generic enough to be confusing) - `pulse.type` vs `type(pulse.channel)`

**Comment by AleCandido** [comment]
It seems like `modulated_waveforms` is only used by Qblox
https://github.com/search?q=repo%3Aqiboteam/qibolab%20modulated_waveforms&type=code
https://github.com/search?q=repo%3Aqiboteam%2Fqibolab+modulated_waveform_i&type=code
https://github.com/search?q=repo%3Aqiboteam%2Fqibolab+modulated_waveform_q&type=code

Since this generates quite some overhead in `pulses.py`, i.e.
- aliases for IQ
    https://github.com/qiboteam/qibolab/blob/974531413fdc53d9fcb476e375809ab5127bb029/src/qibolab/pulses.py#L151-L161
- wrappers
    https://github.com/qiboteam/qibolab/blob/974531413fdc53d9fcb476e375809ab5127bb029/src/qibolab/pulses.py#L780-L796
- wrappers in subclasses
    https://github.com/qiboteam/qibolab/blob/974531413fdc53d9fcb476e375809ab5127bb029/src/qibolab/pulses.py#L1125-L1129
    https://github.com/qiboteam/qibolab/blob/974531413fdc53d9fcb476e375809ab5127bb029/src/qibolab/pulses.py#L1237-L1259

I would rather get rid of them, even to streamline the interface, and just keep the single modulating method as a standalone function (`PulseShape, num_samples -> (ndarray, ndarray)`), without the serials and all decorations.
Or even `(ndarray, ndarray) -> (ndarray, ndarray)` (envelope -> modulated), essentially like @stavros11 function for Qblox (that at this point I have the feeling it is the inverse, otherwise it's just duplicated...)

https://github.com/qiboteam/qibolab/blob/974531413fdc53d9fcb476e375809ab5127bb029/src/qibolab/instruments/qblox/acquisition.py#L9-L23

What do you think?
@PiergiorgioButtarini @stavros11 @hay-k

**Comment by PiergiorgioButtarini** [comment]
I agree with your analysis and regarding Qblox I don't see any problems if we implement your suggestion mainly because

1. in Qblox there is only the necessity of retrieving the modulated "raw" envelops (so the serials and the other decorations are not used)
2. it is only used when we want to perform software modulation, that for what I understood is a very unlikely scenario and we were discussing also to deprecate this possibility.

**Comment by AleCandido** [comment]
To update everyone involved about it (it is the above mention, but sometimes mentions are not manifest): I was actually convinced that we were not using software modulation anywhere, since only Qblox was implementing it, and apparently not using (as @PiergiorgioButtarini reminded), but @sorewachigauyo is using it in IcarusQ.

Nevertheless, I'm still convinced that we could have a pair of `modulate`/`demodulate` functions, like @stavros11 one:
https://github.com/qiboteam/qibolab/blob/974531413fdc53d9fcb476e375809ab5127bb029/src/qibolab/instruments/qblox/acquisition.py#L9
since we should need nothing more, in general.

**Comment by hay-k** [comment]
If it is not used anywhere, let's just remove them. I am always happy to vote for removing dead code and duplicate code.

If it is used, I think the question where to put this code depends on how much meaning is assigned to the classes `Pulse` and `PulseShape`. Frankly speaking I am not able to understand what exactly those each of these two classes is meant to represent, because there is a loop relationship between them (you need a pulse to define a shape, but to define a pulse you needs a shape), but their combined meaning is pretty straightforward, and those modulation methods do indeed belong to the combined set of those two classes. However, there is still something in those functions that does not belong there - they are technically doing more than modulation, they are sampling. I think, this sampling responsibility does not belong to any of these classes. The question is if we want to change the code so much at this stage to be able to separate sampling from modulation.

**Comment by AleCandido** [comment]
@hay-k I believe the responsibility of the `PulseShape` is pretty clear: provide the callable to implement the shape (`parameters -> time -> signal`). So, the `Rectangular` should just give a constant value in a window defined by parameters, `Gaussian` should return the Gaussian envelope, and so on. Nothing more.

`Pulse` instead is (currently) supposed to be a gateway to the whole pulse, and to me this includes:
1. its unique identification in a sequence
2. hold the parameters (including shape)
3. sample the waveform

To be fair, I don't feel it so wrong. A mild improvement could be to split the three of them (splitting 1. from 2. is the same topic of #716), and we could split 3. by making an enum with possible shapes, and have constructors as values (as we do in other places).
A clear improvement would be to cut `Pulse` out of `PulseShape` (the `.pulse` attribute), and I was proposing this to @stavros11. I'm inclined to open a separate issue, since this might involve further changes (and this issue is already big enough), and it should not be visible from the outside (not sure).

> If it is not used anywhere, let's just remove them. I am always happy to vote for removing dead code and duplicate code.

As I was discussing in #661, it's not bad to have minimal functions doing software demod, since they are occasionally used (and often reimplemented).

> The question is if we want to change the code so much at this stage to be able to separate sampling from modulation.

Modulation should be definitely separate, but sampling the envelope I would keep, why not?
(in the sense that I would keep the callables, that once parametrized should be `time -> envelope`, and possibly NumPy friendly).

**Comment by hay-k** [comment]
> I believe the responsibility of the PulseShape is pretty clear: provide the callable to implement the shape

I think this is still unclear. In a sense this is a recursive sentence, saying "responsibility of shape is to represent the shape". What is the shape? Is it the envelope, or is it the envelope modulated on IF? The fact that the class `PulseShape` contains a pulse (that contains IF) and all those methods for modulation, indicates that the idea behind the current implementation of `PulseShape` is that it represents envelope + IF.

> Modulation should be definitely separate

If you want to strip down the modulation responsibility from `PulseShape`, remove the reference to pulse, and make it simple `PulseEnvelope`, I agree that it is a useful and conceptually correct simplification. In that case you can keep the sampling functionality for the envelope indeed.

But after removing from `PulseShape` where do you put the modulation functionality? Does it go into `Pulse` or somewhere else? I think one needs to clarify the responsibility of  `Pulse`, before answering this question. Doesn't matter what it is now, we can change it as we change the meaning of `PulseShape`, but we need to be clear. Does `Pulse` represent 

1. an envelope + metadata about which qubit, channel or whatever it is? 
2. envelope + IF + metadata? 
3. envelope + IF + RF + metadata? 

Unless it is the first option, I think the modulation functionality belongs to the `Pulse` class. Funny thing is that the docstring of `Pulse` says _"A class to represent a pulse to be sent to the QPU."_, which means it is currently the third option, which it clearly isn't :D

**Comment by AleCandido** [comment]
> I think this is still unclear. In a sense this is a recursive sentence, saying "responsibility of shape is to represent the shape". What is the shape? Is it the envelope, or is it the envelope modulated on IF? The fact that the class `PulseShape` contains a pulse (that contains IF) and all those methods for modulation, indicates that the idea behind the current implementation of `PulseShape` is that it represents envelope + IF.

Sorry, my bad. The envelope in I and Q, this should be unambiguous.
Modulation can always happen on top of the envelope specification, and does not depend on the specific shape of the envelope.

And in practice it's what is happening:
https://github.com/qiboteam/qibolab/blob/47d1d550a32f455fa2cc149820fa0ce06ae96795/src/qibolab/pulses.py#L237
(ok, I don't like so much that is giving directly this weird `Waveform` object, I'd like more a vectorized callable)

> If you want to strip down the modulation responsibility from `PulseShape`, remove the reference to pulse, and make it simple `PulseEnvelope`, I agree that it is a useful and conceptually correct simplification. In that case you can keep the sampling functionality for the envelope indeed.

Ok, then I'd say we agree on this point.

> But after removing from `PulseShape` where do you put the modulation functionality? Does it go into `Pulse` or somewhere else? I think one needs to clarify the responsibility of `Pulse`, before answering this question.

Often, modulation is directly happening on hardware. To the best of my knowledge, everywhere but in IcarusQ (in particular software modulation was introduced for Qblox, which also supports the hardware one, at least now).

In any case, in my mind the demod functions should have just the interface `ienv -> qenv -> freq -> (imod, qmod)` and conversely (where all the `ienv`/.../`qmod` are arrays of the same size, but `freq`). So they could even be standalone functions in the `pulse.py` module, at least in a first stage (or forever).

**Comment by AleCandido** [comment]
> Doesn't matter what it is now, we can change it as we change the meaning of `PulseShape`, but we need to be clear. Does `Pulse` represent
> 
>   1. an envelope + metadata about which qubit, channel or whatever it is?
>   2. envelope + IF + metadata?
>   3. envelope + IF + RF + metadata?
> 
> Unless it is the first option, I think the modulation functionality belongs to the `Pulse` class. Funny thing is that the docstring of `Pulse` says _"A class to represent a pulse to be sent to the QPU."_, which means it is currently the third option, which it clearly isn't :D

Concerning `Pulse`: to me, its fundamental role has to be the 1. in my list above. So, it could even avoid containing the actual envelope as an array, but just the info to build the whole signal (the RF one being played in the channel) in the driver.

Whether this requires to upload an envelope array to the device, or an IF modulated array, or whatever (e.g. even the envelope callable) this will be up to the driver (I know that `laboneq` accepts callables, even though I'd rather avoid - but if it's convenient there is nothing too wrong).

**Comment by hay-k** [comment]
I usually try to keep myself away from debates for or against OOP. I think it is possible to write bad code regardless of paradigm and language. If one does not have clear definitions it is always easy to pile up code where it doesn't belong.

**Comment by AleCandido** [comment]
> I usually try to keep myself away from debates for or against OOP. I think it is possible to write bad code regardless of paradigm and language. If one does not have clear definitions it is always easy to pile up code where it doesn't belong.

Yeah, that was only the succinct summary. Just to say that we don't need functions to necessarily belong to a class, and thus we don't need a class to take responsibility for this feature.

I don't care so much about styles, or better I care about their classification as much as you do. All of them are useful if they could get your job done in a simple, effective, and maintainable way.

**Comment by alecandido** [comment]
Most of the points have been addressed, and there are only a couple in the OP, plus a few ones in the comments below. But I believe they should be addressed in separate issues, also because they might be related to other rework, beyond pulses.

- we agree (at least me and @stavros11) that the `Pulse.type` attribute is redundant, and that it could be inferred from the channel - but this regards how we actually manage channels
- the `.start` related method will be removed following #682, but not before (so I'd delegate to that issue)
- the `PulseShape` rework is worth an issue on its own, since it will change a lot how they are invoked (they are one of the main items of the pulse implementation, and currently the largest file)
- the software modulation related issue will be alleviated by the `PulseShape` rework, but then it could be treated on its own

I will open issues for all of these, and then I would close this issue as soon as all the `simplify-pulse-*` PRs will be merged into `0.2`.

**Comment by alecandido** [comment]
@stavros11 @hay-k @PiergiorgioButtarini I'm closing this issue since it has been mostly addressed, and there are other issues for the remaining points.
