### ISSUE TITLE
Adapt Qblox to drop `waveform.serial`

### ISSUE THREAD

**Issue by PiergiorgioButtarini** [qiboteam/qibolab#780]
Thanks @alecandido! From my side I don't need a readable identifier (like it was `Pulse.serial`), so everything looks good to me. Only problem dropping `waveform.serial` will be a breaking changes for Qblox and I will open an issue in order to solve it asap.

_Originally posted by @PiergiorgioButtarini in https://github.com/qiboteam/qibolab/issues/750#issuecomment-1904397386_

**Comment by alecandido** [comment]
This is partially done, since in 0.2.0 there is not any `waveform.serial` any longer. But the drivers have not been all tested (in particular Qblox).

In any case, it will be automatically completed before merging 0.2.0 (since the original strategy is not possible any longer, and all drivers will be working before merging it).
No need to track this separately.
